version: '3.8'

services:
  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - order-db
      - kafka
      - zookeeper
    environment:
      - MONGO_ORDER_URI=${MONGO_ORDER_URI}
      - MONGO_ORDER_LOGIN=${MONGO_ORDER_LOGIN}
      - MONGO_ORDER_PASSWORD=${MONGO_ORDER_PASSWORD}

  customer-service:
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - customer-db
      - kafka
      - zookeeper
    environment:
      - MONGO_CUSTOMER_URI=${MONGO_CUSTOMER_URI}
      - MONGO_CUSTOMER_LOGIN=${MONGO_CUSTOMER_LOGIN}
      - MONGO_CUSTOMER_PASSWORD=${MONGO_CUSTOMER_PASSWORD}

  order-db:
    image: "mongo"
    ports:
      - "27018:27017"
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ORDER_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ORDER_PASSWORD}
    volumes:
      - order-db-data:/data/db

  customer-db:
    image: "mongo"
    ports:
      - "27019:27017"
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_CUSTOMER_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_CUSTOMER_PASSWORD}
    volumes:
      - customer-db-data:/data/db

  kafka:
    image: "confluentinc/cp-kafka:latest"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://host.docker.internal:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    networks:
      - app-network
    depends_on:
      - zookeeper

  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  order-db-data:
  customer-db-data:
